### PR TITLE
Fixes #9338: permission filters can be created now

### PR DESCRIPTION
**Pull request by witlessbird**

### CODE REVIEW

**Comment by witlessbird** [comment]
[test]

**Comment by eLobato** [comment]
Thanks, the only issue I found is that it's a bit difficult to see the resource_type in the filter list for Docker specific resources. 
  * Can we have something like 'Docker/Container', 'Docker/Registry', etc.. like foreman_salt does?  
  * What resource_type does ImageSearch map to?

**Comment by witlessbird** [comment]
@eLobato: ping

**Comment by eLobato** [comment]
@witlessbird pong. Few issues: 

* For some reason I see properly 'Docker/Container' but ImageSearch and Registry remain the same regardless of the changes, without the prefix. Any ideas?
* I see all of the permissions under the '(Miscellaneous)' resource type additionally to their regular resource type

Test failures are not related to the PR so don't worry.

Thanks!

**Comment by witlessbird** [comment]
@eLobato: can you try deleting docker-related permissions from the db and try again?

**Comment by eLobato** [comment]
Merged as d0846a1ae08b3fffa39d03c74db307875e9e408f, thanks @witlessbird, that worked! :shipit:

**Pull request closed without merging**
