### PR TITLE
Fixes #16235 - Add verify SSL option for Registries

### PR DESCRIPTION
**Pull request by bastilian**
To allow using registries with an invalid certificate
the "Verify ssl" option disables verification for
connections to a registry.

### CODE REVIEW

**Comment by xprazak2** [comment]
I set up simple http registry with the following docker-compose.yml:

```yaml
registry:
  image: registry:2
  ports:
    - 192.168.100.107:5000:5000
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  volumes:
    - ./data:/data
```

'Verify ssl' checkbox is ignored for http registry and the following form does not raise any errors:


Is that intended? I kind of expected 'verify ssl' would complain about url scheme not being https...

**Comment by bastilian** [comment]
@xprazak2 you are right. the "Verify SSL" option has no effect, when the request is not to https, thus won't raise an error. 

It would be nice to just have it hidden by default and it pops up as soon as you hit "httpS", and hide it otherwise again.

Maybe @Rohoover can have a quick look here as well?

**Comment by Rohoover** [comment]
@bastilian I'm not against what you proposed.

**Comment by bastilian** [comment]
@Rohoover The showing of the verification option is now implemented and goes like this:

z7wv9fbigb

@xprazak2 Mind taking another look as well?

**Comment by Rohoover** [comment]
@bastilian 

Thanks! Also - is it possible to put the help text for the fields into Field Level help?

**Comment by bastilian** [comment]
@Rohoover done.

screen shot 2017-06-15 at 11 32 58

The CI failure seems unrelated, but only happens in this branch and seems to be an issue with DataTables.

**Comment by bastilian** [comment]
@dLobatog the last CI failure was due to a version (didn't look into which) was thrown off by a html syntax error. I fixed it, but the table specifically the headers have issues and it adds another filter. See: 
screen shot 2017-06-15 at 15 00 04

Should we simply not make it a DataTable? It seems to be rarely used elsewhere, or?

**Comment by bastilian** [comment]
CI failure on 2.4 is unrelated.

**Pull request merged**
