### PR TITLE
fixes #9332 - Add yes/no text to managed info on containers index

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by eLobato** [comment]
[test]

**Comment by shlomizadok** [comment]
fixed rubocop issue, please [test]

**Comment by eLobato** [comment]
`managed?(container, resource) ? _('Yes') : _('No')` should be enough as @daviddavis said, both the icon and the text is even more confusing in my opinion, you can get rid of the managed_icon helper too and put it directly in the view if you want. 

Thanks @shlomizadok !

**Comment by shlomizadok** [comment]
@eLobato - done. thank you.

**Comment by eLobato** [comment]
Merged as 39e19af1b833e60a91cb150f749ff2e074b9dd7f, thanks @shlomizadok !

**Pull request closed without merging**
