### PR TITLE
Fixes #9570 - Only set username/password/email if present

### PR DESCRIPTION
**Pull request by daviddavis**

### CODE REVIEW

**Comment by eLobato** [comment]
@daviddavis This fixes the problem neatly. When the docker service is up, it works pretty well. However we should handle better what happens when the service is down. Currently:
  * if the service was never started and is off - 500 code: `Excon::Errors::SocketError: No such file or directory - connect(2) (Errno::ENOENT)`
  * if the service was started at some point then turned off - 500 code: `Excon::Errors::SocketError: Connection refused - connect(2) (Errno::ECONNREFUSED)
  * if the service is up - 200 code: everything :ok:

Can you fix that and I'll merge? It kind of breaks my heart but this method is one of the few ocassions where a catch-all `rescue => e` seems fine, as `Errno` exceptions are notoriously unreliable and hard to group.

Thanks again

**Comment by daviddavis** [comment]
@eLobato do you mind if I open [another bug](http://projects.theforeman.org/issues/9595)? These problems currently exist in master and I want to make sure this fix gets into the next nightly as it's blocking people.

**Comment by daviddavis** [comment]
@eLobato I found the problem and updated. It looks like the wrapped memoization code block was causing the exception to not be rescued by [`rescue Excon::Errors::Error`](http://git.io/xWye).

**Comment by daviddavis** [comment]
[test]

**Comment by eLobato** [comment]
Merged as 6789456ca82b33c933fec94f2fc8383edd2779d3, thanks @daviddavis

**Pull request closed without merging**
