### PR TITLE
Fixes #19964 - Use ApplicationRecord instead of ActiveRecord::Base

### PR DESCRIPTION
**Pull request by bastilian**
Not mergable yet, as using `ApplicationRecord` for `DockerContainerWizardState` raises `NoMethodError: undefined method 'has_one' for main:Object`.

Not sure yet why this occurs.

### CODE REVIEW

**Comment by mmoll** [comment]
[test] again after Jenkins plugins updates

**Comment by bastilian** [comment]
[test]

**Comment by bastilian** [comment]
@dLobatog last test run on CI had only two tests failing due to the integration test issue. Unless you object, I think we can merge this.

**Comment by dLobatog** [comment]
Thanks @bastilian !

**Pull request merged**
