### PR TITLE
Fixes #21143: add containers icon for vertical navigation.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/21143

### CODE REVIEW

**Comment by waldenraines** [comment]
Blocked by https://github.com/theforeman/foreman/pull/4794

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
> [test]

Anyone know why this is failing?

**Comment by waldenraines** [comment]
> Anyone know why this is failing?

@dLobatog @bastilian

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
These are failing different configurations each time 😢

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
Maybe the stars will align this time?

[test]

**Comment by waldenraines** [comment]
[test]

**Comment by bastilian** [comment]
@waldenraines sorry for the delay. The test failures are random. We have seen the "DNS issue" with integration tests, but are not sure how to address that. The change is small and I doubt it is the reason for any test failure.

If @dLobatog gives his ok, I'd merge this.

**Comment by waldenraines** [comment]
> @waldenraines sorry for the delay. The test failures are random. We have seen the "DNS issue" with integration tests, but are not sure how to address that. The change is small and I doubt it is the reason for any test failure.
> 
> If @dLobatog gives his ok, I'd merge this.

Thanks @bastilian, we are getting close to merging https://github.com/theforeman/foreman/pull/4794 so we'll want to get this figured out or else end up without an icon for the foreman-docker menu.

**Pull request merged**
