### PR TITLE
Fix test redirect_to_back

### PR DESCRIPTION
**Pull request by dLobatog**

### CODE REVIEW

**Comment by dLobatog** [comment]
http://ci.theforeman.org/job/test_plugin_matrix/4461

**Comment by dLobatog** [comment]
http://ci.theforeman.org/job/test_plugin_matrix/4462

**Comment by ares** [comment]
looks good, please merge :-)

**Comment by ares** [comment]
btw the job now fails on rubocop, maybe you want to add the fix here too...

```
00:23:51 /var/lib/workspace/workspace/test_plugin_matrix/database/sqlite3/ruby/2.4/slave/fast/plugin/test/functionals/image_search_controller_test.rb:21:3: C: Metrics/BlockLength: Block has too many lines. [146/130]
00:23:51   describe '#search_repository' do ...
00:23:51   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by dLobatog** [comment]
The only tests failing are those fixed by https://github.com/theforeman/foreman/pull/5161

http://ci.theforeman.org/job/test_plugin_matrix/4466

**Comment by ares** [comment]
now tests are broken because of audited update, we'll need to retrigger after that's resolved in core

**Pull request merged**
