### PR TITLE
Fixes #15098 - Scope registry by taxonomies

### PR DESCRIPTION
**Pull request by dLobatog**

### CODE REVIEW

**Comment by daviddavis** [comment]
LGTM. Any idea about Jenkins?

**Comment by dLobatog** [comment]
@daviddavis Jenkins needs to have docker tests pass consistently before running them here. It looks like some tests are broken with the latest develop. I'll open a new PR that fixes those, then it'll start testing this PR.

**Comment by dLobatog** [comment]
I think the last update should have the appropriate LOCs to make Mr Jenkins happy again.

**Comment by dLobatog** [comment]
Merged as 10546a552e852d38216e4fe8dae60dfa10777234, thanks @dLobatog!

**Pull request closed without merging**
