### PR TITLE
Fixes #9643 - Added search param to the containers index API

### PR DESCRIPTION
**Pull request by daviddavis**

### CODE REVIEW

**Comment by eLobato** [comment]
:+1: works well, @daviddavis could you add a functional test so it's good to go? Thanks!

**Comment by daviddavis** [comment]
will do. thx!

**Comment by eLobato** [comment]
@daviddavis Missing a rubocop fix and we're done, thanks! :+1:

**Comment by daviddavis** [comment]
@eLobato thx. fixed.

**Comment by eLobato** [comment]
@daviddavis :trophy: , I'll merge as soon as I get in a non-capped connection. Thanks!

**Comment by daviddavis** [comment]
Merged as 271b10e

**Pull request closed without merging**
