### PR TITLE
Refs #7977 - Adjusting class length check in rubocop

### PR DESCRIPTION
**Pull request by daviddavis**

### CODE REVIEW

**Comment by parthaa** [comment]
ack

**Comment by eLobato** [comment]
[test]

**Comment by eLobato** [comment]
Just for the record, I don't think setting an arbitrary number for class length is exactly a great idea. Is a 200 lines class OK but 201 can be bad enough not to merge it? However, ```foreman-docker``` is a small program, I think it would be a bad smell if we started to have 1k lines per class. 

So all in all this cop at least 'forces' us to remove duplication, follow SRI, and tidy up things before getting to this point. As our code base grows, we will likely have to increase it. @witlessbird any opinion on this?

**Comment by eLobato** [comment]
Merged as 0fdc54a8492ac063dcff003f163a86f776490721, thanks @daviddavis

**Pull request closed without merging**
