### PR TITLE
update all the things...

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
includes GH-202

**Comment by mmoll** [comment]
http://ci.theforeman.org/job/test_plugin_pull_request/4429/

**Comment by mmoll** [comment]
14 test failures left... as I have no idea of foreman-docker, I'll leave this to the plugin maintainers.

One thing that's needed for sure is a change like https://github.com/theforeman/foreman/commit/a0969d71c1c569eff30e792726b9fb081b2ee34c

**Comment by ehelms** [comment]
LGTM! Hopefully @bastilian or @dLobatog can find time to look at this so we can get a release out soon

**Comment by dLobatog** [comment]
Thanks @mmoll !

**Pull request merged**
