### PR TITLE
[DON'T MERGE] - Testing out HoundCI

### PR DESCRIPTION
**Pull request by daviddavis**
This should pass rubocop/houndci but it won't. See http://projects.theforeman.org/issues/9708 for more info.

### CODE REVIEW

**Comment by daviddavis** [comment]
@eLobato why does houndci pass if I have code problems?

**Comment by eLobato** [comment]
@daviddavis No idea why is it green.. I tweeted at them with this link as it's their support channel according to houndci.com

**Comment by eLobato** [comment]
@daviddavis Oh I think I see what's going on, see the current status of https://github.com/theforeman/foreman-docker/pull/100 , Hound :white_check_mark:  means that it reviewed the changes, it doesn't mean that the code doesn't contain any rubocop mistakes.

**Comment by croaky** [comment]
Yes, right now Hound only creates pending and success statuses:

https://github.com/thoughtbot/hound/blob/master/app/services/build_runner.rb#L9-L17

I can see how that would be confusing and we'll look into improving it.

**Comment by eLobato** [comment]
Thanks @croaky for the clarification! @daviddavis if you don't mind I'll close it as the issue has been resolved..

**Pull request closed without merging**
