### PR TITLE
Fixes #21529 - start using factory bot

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
rubocop needs to be updated first

**Comment by ares** [comment]
and there's some failing test in master http://ci.theforeman.org/job/test_plugin_matrix/4000/database=postgresql,ruby=2.2,slave=fast/testReport/junit/(root)/ContainerStepsTest__on%20image%20step__on%20hub%20tab__autcomplete__for%20tag/test_0001_it_searches_for_tags/

**Comment by mmoll** [comment]
This got in with e16d4ca

**Comment by ares** [comment]
nvm... I hope someone has noticed that tests are broken, I retriggered the jenkins job as it seems as some js timeout, probably worth of adding retry concern

**Pull request closed without merging**
