### PR TITLE
Fixes #11984 - Some changes to complete i18n.

### PR DESCRIPTION
**Pull request by bkearney**
Once this is reviewed/merged, please ask upstream to send the strings (PO and POT files)
to transifex

### CODE REVIEW

**Comment by bkearney** [comment]
@dLobatog I rebased this to 2.0

**Comment by bkearney** [comment]
@dLobatog I have updated this based on the construction day. This may be a slight overlap with https://github.com/theforeman/foreman-docker/pull/116.

**Comment by bkearney** [comment]
@orrabin @stbenjam updated per today

**Comment by bkearney** [comment]
@dLobatog any chance of getting this in this week?

**Comment by dLobatog** [comment]
Merged as 792d601d5c214e5bba2f26f6291f5dde24232b67, thanks @bkearney!

**Pull request closed without merging**
