### PR TITLE
Fixes #20067 - Wrong constant name Docker/ImageSearch

### PR DESCRIPTION
**Pull request by dLobatog**

### CODE REVIEW

**Comment by ares** [comment]
I'm afraid we'll need a migration for users that already have this permission in their DB. After I deleted it manually, it was created just fine.

**Comment by ares** [comment]
I triggered tests on master as they failed since core develop was broken at that time (excon)

**Comment by mmoll** [comment]
these will fail until http://theforeman.org/issues/22065 got resolved

**Comment by ares** [comment]
I guess this is now blocked by #207 but then, :+1: for merging this one (I don't have permissions here)

**Comment by ares** [comment]
sorry, master is still broken :-/ http://ci.theforeman.org/job/test_plugin_matrix/4467/ I've retriggered the run just to be sure http://ci.theforeman.org/job/test_plugin_foreman_docker_master/243/

**Comment by dLobatog** [comment]
I'm going to go with merging as the failing integration tests all fail with the all too common "Capybara::Poltergeist::StatusFailError: Request to 'http://127.0.0.1:45577/hosts/new' failed to reach server, check DNS and/or server status"

**Pull request merged**
