### PR TITLE
Fixes #9716 - Handle '1.8.0-rc1' version format

### PR DESCRIPTION
**Pull request by daviddavis**

### CODE REVIEW

**Comment by domcleal** [comment]
There's another instance circa line 103, could you update that too please?

**Comment by domcleal** [comment]
Tests fine on 1.8.0-RC1 when I fix the other instance too.

**Comment by daviddavis** [comment]
@domcleal done.

**Comment by domcleal** [comment]
Merged as 9781b90, thanks @daviddavis!

**Pull request closed without merging**
