### PR TITLE
Fixes #8815 by correcting wrong variable reference in template

### PR DESCRIPTION
**Pull request by dragonfly9517**

### CODE REVIEW

**Comment by eLobato** [comment]
@dragonfly9517 Can you change just the name of the local variable passed in the image search controller to "repositories"?

**Comment by dragonfly9517** [comment]
@eLobato  : Done !!

**Comment by dragonfly9517** [comment]
@eLobato  : On a different note, I dont think I have been added to the automated testing whitelist only because I was added to the foreman organization. As it looks like by reading up [here](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin) , someone has to probably specifically add me to the automated testing whitelist, by a comment matching or a particular regex or probably in the admin interface of jenkins.

**Comment by eLobato** [comment]
[test]

**Comment by eLobato** [comment]
@dragonfly9517 Yes you are in the list, but your membership is private. You need to make it public for Jenkins to pick up your user name and test pull requests.

https://help.github.com/articles/publicizing-or-concealing-organization-membership/

**Comment by dragonfly9517** [comment]
Thanks @eLobato  !! My membership is now public :)

**Comment by eLobato** [comment]
Merged as 44602d1e0f09967a57cc094b41226891f168f0f9,  I made some styling changes to make it Rubocop compliant, thanks @dragonfly9517 !

**Pull request closed without merging**
