### PR TITLE
Fixes #13228 - add attr_accessible to enviroment and image

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by orrabin** [comment]
this was changed to include ':katello' in image.rb, leftovers from https://github.com/theforeman/foreman-docker/pull/135

**Comment by ehelms** [comment]
Confirm it leads to passing Katello tests, thanks @orrabin

**Comment by thomasmckay** [comment]
ACK, works for me

**Comment by dLobatog** [comment]
Merged as 8627992a6b85d79b4f042d79f7d21eac622b900b, thanks @orrabin!

**Pull request closed without merging**
