### PR TITLE
Fixes #13225: Don't declare spinner.gif with /assets prefixed

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
This was found in the course of running Katello tests where we integrate with foreman-docker views.

**Comment by thomasmckay** [comment]
ACK

**Comment by dLobatog** [comment]
Merged as bd43acfd73f361d174018f92ab70ef9c6123a48f, thanks @ehelms!

**Comment by ehelms** [comment]
I have another PR incoming that I also uncovered but was a different issue than this. I mention that because it would be nice to get a new gem with all these fixes to then get katello tests passing.

**Pull request closed without merging**
